### ISSUE TITLE
Includes are broken

### ISSUE THREAD

**Issue by ydixken** [bitslip6/rpi-gpu-hub75-matrix#1]
Currently the project can't be build due to errors within the header includes, also `myapp.c` was renamed to `main.c`. 

```bash
ydixken@raspberrypi:~/rpi-gpu-hub75-matrix $ make clean
rm -rf build
rm -f build/util.o build/pixels.o build/rpihub75.o build/gpu.o librpihub75.so librpihub75_gpu.so
ydixken@raspberrypi:~/rpi-gpu-hub75-matrix $ git reset --hard
HEAD is now at f767264 fix example
ydixken@raspberrypi:~/rpi-gpu-hub75-matrix $ make
mkdir -p build
gcc -DNDEBUG=1 -std=gnu2x -fPIC -ffast-math -fopt-info-vec -funroll-loops -ftree-vectorize -mtune=native -O3 -Wall -Wpedantic -Wdouble-promotion -Iinclude -c src/util.c -o build/util.o
src/util.c: In function ‘binary64’:
src/util.c:130:24: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
  130 |         fprintf(fd, "%ld", (number >> i) & 1);
      |                      ~~^   ~~~~~~~~~~~~~~~~~
      |                        |                 |
      |                        long int          uint64_t {aka long long unsigned int}
      |                      %lld
In file included from include/util.h:4,
                 from src/util.c:16:
src/util.c: In function ‘map_gpio’:
include/rpihub75.h:84:23: warning: overflow in conversion from ‘long long int’ to ‘__off_t’ {aka ‘long int’} changes value from ‘133144838144’ to ‘851968’ [-Woverflow]
   84 |     #define PERI_BASE 0x1f000D0000
      |                       ^~~~~~~~~~~~
src/util.c:240:9: note: in expansion of macro ‘PERI_BASE’
  240 |         PERI_BASE
      |         ^~~~~~~~~
src/util.c:245:36: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘long long int’ [-Wformat=]
  245 |         printf("mmap failed: %s [%ld] / [%lx]\n", strerror(errno), PERI_BASE, PERI_BASE);
      |                                  ~~^
      |                                    |
      |                                    long int
      |                                  %lld
src/util.c:245:44: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘long long int’ [-Wformat=]
  245 |         printf("mmap failed: %s [%ld] / [%lx]\n", strerror(errno), PERI_BASE, PERI_BASE);
      |                                          ~~^
      |                                            |
      |                                            long unsigned int
      |                                          %llx
src/util.c:283:21: optimized: basic block part vectorized using 16 byte vectors
src/util.c:336:23: optimized: basic block part vectorized using 4 byte vectors
src/util.c:336:23: optimized: basic block part vectorized using 4 byte vectors
src/util.c:336:23: optimized: basic block part vectorized using 4 byte vectors
src/util.c:581:28: optimized: basic block part vectorized using 4 byte vectors
gcc -DNDEBUG=1 -std=gnu2x -fPIC -ffast-math -fopt-info-vec -funroll-loops -ftree-vectorize -mtune=native -O3 -Wall -Wpedantic -Wdouble-promotion -Iinclude -c src/pixels.c -o build/pixels.o
gcc -DNDEBUG=1 -std=gnu2x -fPIC -ffast-math -fopt-info-vec -funroll-loops -ftree-vectorize -mtune=native -O3 -Wall -Wpedantic -Wdouble-promotion -Iinclude -c src/rpihub75.c -o build/rpihub75.o
gcc -DNDEBUG=1 -std=gnu2x -fPIC -ffast-math -fopt-info-vec -funroll-loops -ftree-vectorize -mtune=native -O3 -Wall -Wpedantic -Wdouble-promotion -Iinclude -shared -o librpihub75.so build/util.o build/pixels.o build/rpihub75.o  -lpthread -lrt -lm -lc
gcc -DNDEBUG=1 -std=gnu2x -fPIC -ffast-math -fopt-info-vec -funroll-loops -ftree-vectorize -mtune=native -O3 -Wall -Wpedantic -Wdouble-promotion -Iinclude -c src/gpu.c -o build/gpu.o
gcc -DNDEBUG=1 -std=gnu2x -fPIC -ffast-math -fopt-info-vec -funroll-loops -ftree-vectorize -mtune=native -O3 -Wall -Wpedantic -Wdouble-promotion -Iinclude -shared -o librpihub75_gpu.so build/util.o build/pixels.o build/rpihub75.o build/gpu.o -lpthread -lrt -lm -lc `pkg-config --libs glesv2 gbm egl`

ydixken@raspberrypi:~/rpi-gpu-hub75-matrix $ gcc -lrpihub75_gpu main.c -o main 
/usr/bin/ld: /tmp/ccu4MEVu.o: in function `render_cpu':
main.c:(.text+0xe0): undefined reference to `draw_square'
/usr/bin/ld: /tmp/ccu4MEVu.o: in function `main':
main.c:(.text+0x13c): undefined reference to `default_scene'
/usr/bin/ld: main.c:(.text+0x148): undefined reference to `check_scene'
/usr/bin/ld: main.c:(.text+0x18c): undefined reference to `render_forever'
/usr/bin/ld: main.c:(.text+0x194): undefined reference to `render_shader'
collect2: error: ld returned 1 exit status

```

**Comment by bitslip6** [comment]
Thanks for giving this a shot.  I am pushing the dev branch to master in a half hour. includes:

build fixes. fresh install fixes. build instructions for building a realtime kernel. additional shaders. 64 bit BCM (PWM) data. image dithering. additional tone mapping functions.  image mapping functions (mirror, flip, mirror_flip). improved drawing functions: check include/pixels.h - all drawing functions begins with hub_.

next release:
anti-aliased true type fonts using singed distance fields.  mpeg video support via ffmpeg.



The gradients are still a work in progress.

to set a color:
RGB color = {255, 0, 128};   // R, G, B - redish purple
hub_pixel(scene, x, y, color);

// draw circle:
void hub_circle(scene_info *scene, const uint16_t width, const uint16_t height, const uint16_t centerX, const uint16_t centerY, const uint16_t radius, const RGB color);

// draw line bresenham:
void hub_line(scene_info *scene, int x0, int y0, int x1, int y1, RGB color);
// draw anti-aliased line (wu):
void hub_line_aa(scene_info *scene, const int x0, const int y0, const int x1, const int y1, const RGB color);
// draw pixel
void hub_pixel(scene_info *scene, const int x, const int y, const RGB pixel);
// draw anti-aliased pixel
inline void hub_pixel_factor(scene_info *scene, const int x, const int y, const RGB pixel, const float factor);

**Comment by ydixken** [comment]
> Thanks for giving this a shot.

Of course! :-) 

Alright, I'm ready to test. Quick question: Do you work with an Adafruit hat like [with the hzeller](https://github.com/hzeller/rpi-rgb-led-matrix/?tab=readme-ov-file#if-you-have-an-adafruit-hat-or-bonnet ) lib or are you using the plain GPIOs without a hat?

**Comment by bitslip6** [comment]
using the hzeller hat from https://www.electrodragon.com/product/rgb-matrix-panel-drive-board-raspberry-pi/

okay. I think all is good now.  Let me know how it goes for you.

**Comment by bitslip6** [comment]
Oh, I only support A.B,C,D,E address lines at the moment.  if you have different address line send a link to your adapter board and I'll try to add support.

**Comment by ydixken** [comment]
It's this bonnet: https://www.adafruit.com/product/2345 / https://learn.adafruit.com/adafruit-rgb-matrix-plus-real-time-clock-hat-for-raspberry-pi/downloads - also trying to dig through the pinout right now. No image yet visible, but able to run the binary

**Comment by bitslip6** [comment]
Okay when I get back to the house I'll see if I can find the pin mappings and add support

**Comment by ydixken** [comment]
Thanks! Highly appreciated, will test in the morning! Also got a lot of 64x64 panels laying around.

**Comment by bitslip6** [comment]
Looks pretty simple. All of the pins are #define for compiler optimization so it will need to be specified at build time.
I'll add an option tomorrow.

For now you can edit pin mappings in rpihub75.h

Use the pin mappings from the lady ada docs and edit address_clk, address_oe, address_latch and all of the address_p0_xx defines to point to the pins on your board.

Make clean
Make
sudo Make Iinstall


If you have a scope, you can connect the scope to your output pins to verify operation.  The Readme has a section on the hub75 operation.  Render_forever has the code to pump the data out so that might help as well.

**Comment by bitslip6** [comment]
Looks pretty simple. All of the pins are #define for compiler optimization so it will need to be specified at build time.
I'll add an option tomorrow.

For now you can edit pin mappings in rpihub75.h

Use the pin mappings from the lady ada docs and edit address_clk, address_oe, address_latch and all of the address_p0_xx defines to point to the pins on your board.

Make clean
Make
sudo Make Iinstall


If you have a scope, you can connect the scope to your output pins to verify operation.  The Readme has a section on the hub75 operation.  Render_forever has the code to pump the data out so that might help as well.

**Comment by bitslip6** [comment]
sorry I pushed a regression last night that was not setting the output pin modes correctly. I only noticed this when I rebooted.  I just checked in a fix that also includes support for the ada fruit hat.  I really recommend you get the electro dragon hat or one from hzeller.

to compile for the ada fruit hat:
 
git pull
make clean
make DEF="-DADA_HAT=1"
sudo make install
./example -x 64 -y 64 -p 1 -c 1 -f 160 -o -d 64 -b 250 -t aces -l 2.0 -g 2.4 -s shaders/happy_jump.glsl -i mirror_flip

I haven't yet implemented U mapping or V mapping, but if you look at the mirror_flip code you should be able to implement one.  maybe later this week.

**Comment by bitslip6** [comment]
Any update?
